### ISSUE TITLE
Upload failed: AttributeError: module 'posixpath' has no attribute 'remove' (Andrea Bocelli, Compilation)

### ISSUE THREAD

**Issue by Valin8343** [MADindustries/Uploafer#6]
```
sandbox@sandbox:~/Uploafer$ python3 uploafer.py -vv -r -t 1037226
INFO: Debug output.
DEBUG: Currently processing [1/1]: /store/nasa/Temp/wcd/1037226
DEBUG: Starting new HTTPS connection (1): passtheheadphones.me
DEBUG: https://passtheheadphones.me:443 "POST /login.php HTTP/1.1" 302 None
DEBUG: https://passtheheadphones.me:443 "GET /index.php HTTP/1.1" 200 None
DEBUG: https://passtheheadphones.me:443 "GET /ajax.php?action=index HTTP/1.1" 200 None
DEBUG: Artist search: Andrea Bocelli
DEBUG: https://passtheheadphones.me:443 "GET /ajax.php?action=artist&auth=xxx&artistname=Andrea+Bocelli HTTP/1.1" 200 None

1 - No match found for "Providence" [CD/Lossless]:  /store/nasa/Temp/wcd/1037226
Closest match (44% likeness): Passione
Do you want to upload to artist "Andrea Bocelli" [https://passtheheadphones.me/artist.php?id=15662]? [y/N] y
DEBUG: https://passtheheadphones.me:443 "GET /ajax.php?action=index&auth=xxx HTTP/1.1" 200 None
DEBUG: https://passtheheadphones.me:443 "POST /upload.php HTTP/1.1" 200 None
ERROR: Upload failed! View request output at failed-1037226.html
Traceback (most recent call last):
  File "uploafer.py", line 400, in <module>
    main()
  File "uploafer.py", line 390, in main
    dataPath = uploadTorrent(ri, session)
  File "uploafer.py", line 234, in uploadTorrent
    os.path.remove(torrentPath)
AttributeError: module 'posixpath' has no attribute 'remove'
```

Error: You must enter at least one tag. Maximum length is 200 characters.

**[ReleaseInfo2.txt](https://github.com/MADindustries/Uploafer/files/659601/ReleaseInfo2.txt)**

**Comment by MADindustries** [comment]
Error: You must enter at least one tag. Maximum length is 200 characters.

I need to implement a check that determines whether tags are included in the ReleaseInfo.
